server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: primary
          uri: http://localhost:8081/
          Predicates:
            - Path=/api/verve/**
        - id: secondary
          uri: http://localhost:8082/
          Predicates:
            - Path=/api/verve/**
  main:
    web-application-type: reactive